### ISSUE TITLE
IN file BrainSegDCNN_2.py

### ISSUE THREAD

**Issue by Jiyya** [cvdlab/nn-segmentation-for-lar#1]

**Comment by ujjwalbaid0408** [comment]
Which file you run to get  lables and tranning_PNG files? How much time it takes? Where to set the path for database?

**Comment by Jiyya** [comment]
file name "brain_pipeline" placed inside folder "pre_processing" help me to get labels and training PNG. however, it only takes 5 mints at maximum. you have to set paths in   brain_pipeline at the end where main function starts.

**Comment by ujjwalbaid0408** [comment]
Thanks for the reply. Which database you have used(BRATS13 / BRATS 15)? Do we need to arrange the database in some specific format?

**Comment by tiantian-li** [comment]
I am running the "brain_pipeline" in python 2 using Pycharm IDE, however ,the error is occurred :   IndexError: list index out of range
I know the list is empty, but i don't know the reason .
Sincerely  hope to get your help, thanks

**Comment by Jiyya** [comment]
i am facing same problem kindly pre-create some folders like Labels, norm_PNG, training_PNG, Training_data, n4, norm, n4_PNG, train_data. 

    On Monday, August 21, 2017 12:53 PM, tiantian-li <notifications@github.com> wrote:
 

 I am running the "brain_pipeline" in python 2 using Pycharm IDE, however ,the error is occurred : IndexError: list index out of range
I know the list is empty, but i don't know the reason .
Sincerely hope to get your help, thanks—

**Comment by tiantian-li** [comment]
I have run this code without any error by  converting          scans  [flair[0], =t1[0], t1[1], t2[0], gt[0]]    into        scans = [flair[0], t1[0], t1[1],t2[0]],because my database is without ground truth. However ,i don't know which code i should run in the next.  @Jiyya

**Comment by tiantian-li** [comment]
I run the code ,but the images  I used have  low contrast. I can't download the BraTS 2013 and BraTS 2015 datasets, sincerely hope you can help me for the datasets

**Comment by Cesarec88** [comment]
@tiantian-li  try this [link](https://figshare.com/articles/BRATS_2013_Leaderboard_and_Test_Datasets/1348692) for dowload BRATS2013

**Comment by tiantian-li** [comment]
I don't get the BRATS2013 ,the content of the link I open is "Non-Image content-type returned",whether i need a specific browser to open it @Cesarec88

**Comment by Cesarec88** [comment]
try now

**Comment by Cesarec88** [comment]
i've added a missing CNN  for Brain Tumor Segmentation (the one i was working on) you can give it a look

**Comment by tiantian-li** [comment]
Thanks for your reply and sharing @Cesarec88

**Comment by tiantian-li** [comment]
I run the "brain_pipeline" with BRATS2013, but there is a warning that all .PNG are  low contrast images and the images  obtained are all black, I can't find the reason. I also run the "patch_library", but I don't get the expected results while the code is without any error.
Can anyone please tell me what I should do? Thanks.

**Comment by Cesarec88** [comment]
@tiantian-li  is normal that some images are in low contrast, because the brain_pipeline creates all stripe containing all different modalities from the brain base to the bottom and a little beyond.
You have also to consider that not all patients images are consistent due to the quality of the image itself or the different format in the property extraction.
See carefully if some patients datas are consistent.
Also you can try to manipulate the shape extraction how it appear in the naldeborgh7575 link
[https://github.com/naldeborgh7575/brain_segmentation](https://github.com/naldeborgh7575/brain_segmentation)

**Comment by tiantian-li** [comment]
Thanks for your reply. But when I run the "patch_library", I don't get any result, can you tell me how to do? @Cesarec88

**Comment by Cesarec88** [comment]
Can you be more precise? 
It can be becuase of several reasons:
- is selecting the wrong patches (check if is outputting consistent datas)
- is not saving files in the correct path (check saving path)
- is not learning enough (increase number of patches)
- etc..

**Comment by tiantian-li** [comment]
I am meeting the same problem , by running file "BrainSegDCNN_2.py " i am getting error
with open(model_toload) as f:
FileNotFoundError: [Errno 2] No such file or directory: './first_cascade_model(lecun_init).json'.
I want to know whether you have solved it , and can you tell me the reason and the solution. Sincerely thanks for your help. @Jiyya

**Comment by Jiyya** [comment]
i am not runnig any seg file right now, 
i am getting error in brainpipeline file 
its not creating pipelines for all patients available in BRATS 2015 dataset. it gives error on 4oth patients. i have tried again by removing 40h folder and its nearby folders. however, the issue remains same. its kind of limitation which i could not find.
do u successfully run brain_pipeline file and get images in norm_png, reg_png, training_png folders??? 
do u able to successfully run n4ITK in ur code?

**Comment by Jiyya** [comment]
I have run this code without any error by converting scans [flair[0], =t1[0], t1[1], t2[0], gt[0]] into scans = [flair[0], t1[0], t1[1],t2[0]],because my database is without ground truth. However ,i don't know which code i should run in the next. @Jiyya
--
if someone have groundtruth as well 
how they can solve this issue?

**Comment by dudu114** [comment]
I first run the n4_bias_correction.py ,the result is "INPUT from ipython: run n4_bias_correction input_image dimension n_iterations(optional, form:[n_1,n_2,n_3,n_4]) output_image(optional)".Ialso run the brain_pipeline.py,i get the error "IndexError: list index out of range" .If i run the code by converting scans [flair[0], =t1[0], t1[1], t2[0], gt[0]] into scans = [flair[0], t1[0], t1[1],t2[0]], it can get results without any error ,but the images obtained are all black. I am running the code with BRATS2013 in python2.7. Idon't know how to  solve this problem.If anyone have run the complete codes successfully,and  i hope someone can kindly help me to solve it.

**Comment by tiantian-li** [comment]
@Jiyya I try to add a file named  "VSD.Brain.XX.O.MR_more",and i get the results in the first run, but when running again, the image is all black. I have been trying to delete the  results before , but still can not get the result.I wonder if i get the correct answer when the file is right.

**Comment by dudu114** [comment]
@Cesarec88 Iam running brain_pipeline.py with brats2015 in python2.7，and ican run the code without any error ,but the images gotten are all black,i don't know why.Could you please help me to solve it?Thanks

**Comment by Cesarec88** [comment]
@dudu114 which line command you are executing in the file?
 all 'labels' images are all black due to the code saving format, but for the code execution it's not an issue.

**Comment by dudu114** [comment]
@Cesarec88 I have gotten the Labels and Training_png and run the training phase.Now ,Iam trying to run the testing phase,but i have a doubt : i can't convert .mha to .png by brain_pipeline because there is no the file 'more' in the testing database.py,so i do it by image_png_converter.py,but it can't get all test_data. I want to know how can i get the complete test_data.Thanks

**Comment by Cesarec88** [comment]
The 'more' file is the Ground Truth file(aka where are the labels), if you have the same file but with another name  and is still a .mha format,  you can simply change the name between asterisks at line 87 in brain_pipeline.py file.
