### ISSUE TITLE
The output of  brain_pipeline.py cannot be displayed correctly

### ISSUE THREAD

**Issue by dudu114** [cvdlab/nn-segmentation-for-lar#11]
In the brain_pipeline.py, some patients' images can't show correctly. After debugging, the output of line 101 is found to have many kinds of results. If the output is (176,216,160), the images can show correctly, but if the output is not (176,216,160), the images are all black. I don't know why this happened, why the outputs of line 101 are different, and how can I solve this problem? Thanks

**Comment by Cesarec88** [comment]
Because the shape is different the mask set the solution for different dimensions,so to solve this problem just set the mask output correct in the predict function
