### ISSUE TITLE
How the number of patches are so less?

### ISSUE THREAD

**Issue by gunju** [cvdlab/nn-segmentation-for-lar#12]
Hi, I am a nebiw in medical image segmentation using Deep learning.
You have mentioned that the patches used per class are 10000. So, in total, 50000 patches has to be used for segmentation. Right?
So, have you taken 50000 patches per slice or from whole dataset?

**Comment by Cesarec88** [comment]
From all dataset, the patch creator run above all the dataset searching for patches of a certain class and after augmenting in with a rotation of a desired angle stores it for after using in the learning process
