### ISSUE TITLE
Is the labels you generated through brain_pipeline.py all black?

### ISSUE THREAD

**Issue by tanggirltt** [cvdlab/nn-segmentation-for-lar#13]
hello.I used BRASTS 2015.My generated labels are all black.This is the prompt after running :_UserWarning: Labels/15_150L.png is a low contrast image_  I don't know if it will affect the training of the later model.Could you please explain it?Thank you very much!

**Comment by Cesarec88** [comment]
Hello, 
well, labels are not black, but because the classification goes 0 up to 5 all over the images and  unless one image has pixel mapping between -128, + 128 , the 'visualization' of the label image will look black becuase 0,1,2,3,4,5 means very dark in the pixel representation.
