### ISSUE TITLE
In brain pipeline creation 

### ISSUE THREAD

**Issue by Jiyya** [cvdlab/nn-segmentation-for-lar#3]
![1](https://user-images.githubusercontent.com/29980190/32144619-67505eb6-bcdd-11e7-8f52-1cf4782dfc3b.png)
Can anyone help me to solve this problem?
i am running BRATas dataset but this only make slices for first 38 patients
how i can get slices for complete data set?

**Comment by Cesarec88** [comment]
You have this mismatch error due to all different .mha format given in all medical images. The code don't resolve this exception(in other words we tent to use only files in which conversion is available). You can resolve this in two possible ways:
1. removing patients folders that make this problem
2. modifying the code in order to change the extraction dimension at lines 83/84, each time an exception it present
 bests

**Comment by Jiyya** [comment]
i have already tried this by removing 40th patient folder. however, this give error on 4oth patient, whatever the folder is. i think its limitation in code that this wil only convert first 39 patients.Thanks for reply , i will try setp two as well 

    On Monday, October 30, 2017 6:52 PM, Cesare <notifications@github.com> wrote:
 

 You have this mismatch error due to all different .mha format given in all medical images. The code don't resolve this exception(in other words we tent to use only files in which conversion is available). You can resolve this in two possible ways:   
   - removing patients folders that make this problem
   - modifying the code in order to change the extraction dimension at lines 83/84, each time an exception it present   
bests

**Comment by Jiyya** [comment]
modifying the code in order to change the extraction dimension at lines 83/84, each time an exception it present
can u plz help me line 83/84 of brain pipeline file? def _normalize(self, slice):
    '''
    INPUT:  (1) a single slice of any given modality (excluding gt)
            (2) index of modality assoc with slice (0=flair, 1=t1, 2=t1c, 3=t2)
    OUTPUT: normalized slice
    '''
    b, t = np.percentile(slice, (0.5,99.5))
    slice = np.clip(slice, b, t)
    if np.std(slice) == 0:
        return slice
    else:
        return (slice - np.mean(slice)) / np.std(slice)
what changes should i do in this ?

 

    On Monday, October 30, 2017 6:52 PM, Cesare <notifications@github.com> wrote:
 

 You have this mismatch error due to all different .mha format given in all medical images. The code don't resolve this exception(in other words we tent to use only files in which conversion is available). You can resolve this in two possible ways:   
   - removing patients folders that make this problem
   - modifying the code in order to change the extraction dimension at lines 83/84, each time an exception it present   
bests
