### ISSUE TITLE
the "more" of testing dataset in brats2015 can't be downloaded

### ISSUE THREAD

**Issue by dudu114** [cvdlab/nn-segmentation-for-lar#9]
I downlod the testing dataset from the "more" of testing in brats2015 can't be downloaded,I find the dataset can be downloaded  in addition to the "more".Also i find the type of the "more" file is .nii, which is different from the others. I don't know how to download the total dataset,can you help me to slove the problem? Thanks

**Comment by Cesarec88** [comment]
"more" it's referring at the Ground Truth of the Dataset, nothing more. Bests
